### ISSUE TITLE
Fleshmend does jack shit

### ISSUE THREAD

**Issue by checkraisefold** [Donkstation/Donkstation#38]
Round ID: 7307, but it has done it in like every ling round I've had

## Reproduction:
Fleshmend barely heals you then immediately goes away. A waste of 25 chemicals.

Repro steps:
1. Use fleshmend
2. Become incredibly disappointed

**Comment by kannthus** [comment]
Heya,

Checked the code and it heals 2.5 Brute/Fire/Oxy/Clone/Toxic damage every tick for 10 seconds. It does not apply when the subject is on fire.

I replicated being a changling, applied damage to myself and it healed it fine and lasted exactly as long as stated in the code. Not sure if this is an issue, but if you are suggesting it get buffed thats something that can be looked into I suppose, have any idea what kind of numbers you were expecting?

**Comment by Zonespace27** [comment]
Unable to reproduce bug in any way
